package com.pigmypay.PSolutions.model;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "transactions", indexes = {
        @Index(name = "idx_tx_tenant", columnList = "tenant_id"),
        @Index(name = "idx_tx_agent_status", columnList = "agent_id, settlementStatus"),
        @Index(name = "idx_tx_customer", columnList = "customer_id")
})
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "agent_id", nullable = false)
    private User agent;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false, length = 20)
    private String transactionType; // DEPOSIT or WITHDRAWAL

    @Column(nullable = false, length = 20)
    private String paymentMode;     // CASH, UPI, NONE

    @Column(nullable = false)
    private LocalDateTime transactionDate = LocalDateTime.now();

    @Column(nullable = false, length = 20)
    private String syncStatus = "SYNCED";

    @Column(nullable = false, length = 50)
    private String transactionCategory = "SAVINGS_DEPOSIT"; // SAVINGS_DEPOSIT, LOAN_REPAYMENT, SKIPPED_SHOP_CLOSED

    // 🚨 LEAN SATELLITE LOAN TARGET: Linked strictly as a collection reference point
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loan_id")
    private Loan associatedLoan;

    @Column(nullable = false, length = 20)
    private String settlementStatus = "UNSETTLED"; // UNSETTLED, SETTLED

    @Column(nullable = false)
    private Boolean isReversed = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tenant_id", nullable = false)
    private Tenant tenant;

    // 🚨 IDEMPOTENCY KEY: A unique UUID generated by the Android SQLite database.
    // Prevents double-charging if the mobile app syncs the same data twice.
    @Column(unique = true, length = 100)
    private String offlineAppTxId;
}